name: Run Data Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
    paths:
      - run_page/nike_sync.py
      - run_page/nike_to_strava_sync.py
      - run_page/strava_sync.py
      - run_page/gen_svg.py
      - run_page/garmin_sync.py
      - run_page/coros_sync.py
      - run_page/keep_sync.py
      - run_page/gpx_sync.py
      - run_page/tcx_sync.py
      - run_page/tcx_to_garmin_sync.py
      - run_page/garmin_to_strava_sync.py
      - run_page/keep_to_strava_sync.py
      - run_page/oppo_sync.py
      - run_page/intervals_icu_sync.py
      - requirements.txt

env:
  RUN_TYPE: nike
  ATHLETE: jslyhxq
  TITLE: jslyhxq Running
  MIN_GRID_DISTANCE: 10
  TITLE_GRID: Over 10km Runs
  IGNORE_START_END_RANGE: 10
  IGNORE_POLYLINE: 'ktjrFoemeU~IorGq}DeB'
  IGNORE_RANGE: 10
  SAVE_DATA_IN_GITHUB_CACHE: false
  DATA_CACHE_PREFIX: 'track_data'
  BUILD_GH_PAGES: true
  SAVE_TO_PARQENT: false
  GENERATE_MONTH_OF_LIFE: true
  BIRTHDAY_MONTH: '1989-03'
